[project]
name = "perceptron-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shelly", email = "shellyvermaaa@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
]

[project.scripts]
perceptron-project = "perceptron_project:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
